### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by sjehuda** [strukturart/watermelon#1]
Hello

Does it support the Jabber/XMPP messaging protocol?

**Comment by strukturart** [comment]
No, it very simple peer2peer chat app

**Comment by sjehuda** [comment]
On Mon, 28 Nov 2022 14:31:34 -0800
John-David Deubl ***@***.***> wrote:

> No, it very simple peer2peer chat app
> 

What technology is it based on?

Does it require an intermediate server to begin initial interaction
between two peers?

**Comment by strukturart** [comment]
WebRTC


the server offered by peerJS is used https://peerjs.com/peerserver , but it is also possible to use your own server. the app is not very mature yet, so far you can send text, pictures and your position.

**Comment by sjehuda** [comment]
On Tue, 29 Nov 2022 01:04:28 -0800
John-David Deubl ***@***.***> wrote:

> WebRTC
> 
> 
> the server offered by peerJS is used https://peerjs.com/peerserver ,
> but it is also possible to use your own server. the app is not very
> mature yet, so far you can send text, pictures and your position.
> 
> 
> 

Then Watermelon should be able to communicate with WebCall?
https://f-droid.org/en/packages/timur.webcall.callee/
https://github.com/mehrvarz/webcall-android

**Comment by strukturart** [comment]
yes it should be possible. would you like to fork my app and try it ?
https://webrtc.github.io/samples/

**Comment by sjehuda** [comment]
On Wed, 30 Nov 2022 07:34:40 -0800
John-David Deubl ***@***.***> wrote:

> yes it should be possible. would you like to fork my app and try it ?
> https://webrtc.github.io/samples/
> 

Is it possible to install on postmarketOS or with QEMU or in any way?

I don't have a KaiOS device as of yet.

**Comment by sjehuda** [comment]
Congratulations!

Is it possible to install from bHaCkerStore on Nokia 2780?

**Comment by strukturart** [comment]
@sjehuda If you want to test the latest version, you can send me your IMEI of your KaiOS 2.x device, then I can add you as a tester in the store.
